version: '3'
services:

  dbmysql:
    image: mysql:8.0.22
    command: mysqld --sql_mode=""
    volumes:
      - db-app-name:/var/lib/mysql
    env_file:
      - .env.local
    environment:
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    networks:
      - dev

  phpmyadmin:
    image: phpmyadmin
    env_file:
      - .env.local
    environment:
      PMA_HOST: dbmysql
      MYSQL_DATABASE:
      MYSQL_USER:
      MYSQL_PASSWORD:
      MYSQL_ROOT_PASSWORD:
    ports:
      - "80"
    networks:
      - dev

  app-name: &app-name
    image: app-name
    build: .
    env_file:
      - .env.local
    environment:
      - PHP_CLI_MEMORY_LIMIT="1024M"
    ports:
      - "3200:8080"
    volumes:
      - ./:/var/www
    networks:
      - dev
      - med-search

  xdebug:
    <<: *app-name
    profiles: ["xdebug"]
    env_file:
      - .env.local
      - .env.xdebug
    ports:
      - "3201:8080"
    extra_hosts:
      # https://stackoverflow.com/a/67158212
      # only works with Docker v20.10+
      - "host.docker.internal:host-gateway"

  test:
    <<: *app-name
    profiles:
      - test
    env_file:
      - .env.local
      - .env.test

  redis:
    image: wodby/redis:6
    networks:
      - dev

  s3server:
    image: minio/minio:RELEASE.2021-06-17T00-10-46Z
    command: server /data
    ports:
      - "9000"
    env_file:
      - .env.local
    volumes:
      - ./.vlm/s3server:/data
    networks:
      - dev

networks:
  dev:
    external: false
    name: 'app-name_dev'
  med-search:
    external: true
    name: 'med-search_dev'

volumes:
  db-app-name:
