version: '3'
services:

  app: &app
    image: app
    build:
      context: .
      args:
        UID: ${UID}
        GID: ${GID}
    command: ["rr", "serve", "-c", ".rr.dev.yaml"]
    env_file:
      - .env.local
    environment:
      - PHP_CLI_MEMORY_LIMIT="1024M"
    ports:
      - "8080"
    volumes:
      - ./:/var/www
    networks:
      - dev


  xdebug:
    <<: *app
    profiles: ["xdebug"]
    env_file:
      - .env.local
      - .env.xdebug
    ports:
      - "8080"
    extra_hosts:
      # https://stackoverflow.com/a/67158212
      # only works with Docker v20.10+
      - "host.docker.internal:host-gateway"

  test:
    <<: *app
    profiles:
      - test
    env_file:
      - .env.local
      - .env.test

networks:
  dev:
    external: false
    name: 'app_dev'