name: Build Base PHP docker images

on:
  push:
    branches:
      - 'develop'
      - 'master'
    tags:
      - '**'
  pull_request:
    branches:
      - 'develop'
      - 'master'
    types: [ opened , closed ,  edited , reopened ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref }}
  IMAGE_OWNER: smartmedsa

jobs:
  build-base-php:
    if: ((github.event.action != 'closed' && github.event.pull_request.merged != true))
    uses: ./.github/workflows/docker-build.yml
    with:
      REGISTRY: ghcr.io
      username: ${{ github.actor }}
      IMAGE_OWNER: smartmedsa
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  delete-docker-image:
    if: ((github.event.action == 'closed' || github.event.pull_request.merged == true))
    uses: ./.github/workflows/docker-delete.yml
    with:
      REGISTRY: ghcr.io
      username: ${{ github.actor }}
      IMAGE_OWNER: smartmedsa
      TAG: pr-${{ github.event.number }}
    secrets:
      token: ${{ secrets.SMARTMEDBOT_PAT }}
