name: Build med project docker image

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'packaging_med_project'
    tags:
      - '**'
  pull_request:
    branches:
      - 'develop'
      - 'master'
      - 'packaging_med_project'
    types: [ opened , closed ,  edited , synchronize ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref }}
  IMAGE_OWNER: smartmedsa

jobs:
  build-med-projet:
    if: (!(github.event.action == 'closed' && github.event.pull_request.merged != true))
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Log in to the Container registry"
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/med-projet
          flavor: |
            latest=false

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./med-projet
          file: ./med-projet/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

      - name: run test
        id: test
        run: |
          cd med-projet
          make dcupd
          make dcps
        shell: bash
