name: Build docker image

on:
  push:
    branches:
      - 'master'
      - 'develop'
    tags:
      - '**'
  pull_request:
    branches:
      - 'develop'
      - 'master'
    types: [ opened , closed , reopened ,  edited , synchronize ]
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref }}
  IMAGE_OWNER: smartmedsa


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      -  name: debug PR event
         run: |
           echo "::set-outputs name=e::${{ github.event.pull_request }}"
         shell: bash

      - name: Dump context
        uses: crazy-max/ghaction-dump-context@v1

      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Log in to the Container registry"
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false

      - name: Build and cache
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
