name: Build med project docker image

on:
  push:
    branches:
      - 'master'
      - 'develop'
      - 'delete_image_feature'
    tags:
      - '**'
  pull_request:
    branches:
      - 'develop'
      - 'master'
    types: [ opened , closed ,  edited ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref }}
  IMAGE_OWNER: smartmedsa

jobs:
  build-base-php:
    if: (!(github.event.action == 'closed' && github.event.pull_request.merged != true))
    uses: ./.github/workflows/base-php-workflow.yml
    with:
      REGISTRY: ghcr.io
      username: ${{ github.actor }}
      IMAGE_OWNER: smartmedsa
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}


  build-med-project:
    needs: build-base-php
    if: (!(github.event.action == 'closed' && github.event.pull_request.merged != true))
    uses: ./.github/workflows/med-project-workflow.yml
    with:
      REGISTRY: ghcr.io
      username: ${{ github.actor }}
      IMAGE_OWNER: smartmedsa
      TAG: ${{ needs.build-base-php.outputs.tag }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}


  delete_docker_image:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3

      - name: "Log in to the Container registry"
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ inputs.REGISTRY }}
          username: ${{ inputs.username }}
          password: ${{ secrets.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          flavor: |
            latest=false

      - name: Delete image
        uses: bots-house/ghcr-delete-image-action@v1.0.0
        with:
          # NOTE: at now only orgs is supported
          owner: SmartMedSA
          name: base-php
          # NOTE: using Personal Access Token
          token: ${{ secrets.token }}
          tag: pr-23
