name: Build docker image

on:
  push:
  pull_request:
    branches:
      - 'develop'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref }}
  IMAGE_OWNER: smartmedsa


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Log in to the Container registry"
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 1

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and cache
        uses: docker/build-push-action@v2
        with:
          context: .
          push: ${{ github.event_name == 'pull_request' }}
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_OWNER}}/base-php:latest
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ env.IMAGE_OWNER}}/base-php:buildcache
          cache-to: type=registry,ref=ghcr.io/${{ env.IMAGE_OWNER}}/base-php:buildcache,mode=max


