name: Build docker image

on:
  push:
    branches:
      - 'master'
      - 'develop'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'develop'
      - 'master'


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  IMAGE_TAG: ${{ github.ref }}
  IMAGE_OWNER: smartmedsa


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - id: tagging
        name: Test var
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]
          then
          export TG=pr${{ github.event.number }}
          echo "::set-output name=CTAG::pr${{ github.event.number }}"
          else
          echo "::set-output name=CTAG::${GITHUB_REF##*/}" 
          fi
        shell: bash

      - id: write_tags
        name: write tags
        run: echo ${{ steps.tagging.outputs.CTAG }}

      - name: "Checkout repository"
        uses: actions/checkout@v3
      - name: "Log in to the Container registry"
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and cache
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: .
          push: true
          tags: ghcr.io/smartmedsa/base-php:${{ steps.tagging.outputs.CTAG }}
          labels: ${{ steps.meta.outputs.labels }}