name: Build docker image

on:
  push:
  pull_request:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Build:parentDockerImage"
        run: docker build -t ghrc.io/SmartMedSA/base-php:latest .
